name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: false
        virtualenvs-path: ~/.virtualenvs

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: ~/.virtualenvs
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: make install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: build
      run: poetry build

    - name: Publish a Python distribution to PyPI
      run: poetry publish -n -u "$USERNAME" -p "$PASSWORD"
      env:
        USERNAME: ${{ secrets.pypi_user }}
        PASSWORD: ${{ secrets.pypi_password }}

